sonar.scm.provider=git
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.language=py
sonar.exclusions=Dockerfile
sonar.coverage.exclusions=Dockerfile
sonar.core.codeCoveragePlugin=pytest-cov
sonar.python.coverage.reportPaths=test-results/coverage.xml
sonar.python.xunit.reportPaths=test-results/results.xml
